packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  "@parcel/watcher": true
  vue-demi: true
  sharp: true
  msgpackr-extract: true
  workerd: true
catalog:
  dotenv: ^17.4.2
  zod: ^4.4.3
  typescript: ^6.0.3
  "@types/node": ^26.2.0
  convex: ^1.45.0
minimumReleaseAgeExclude:
  - '@mantine-vue/core@3.4.0'
  - '@mantine-vue/form@3.4.0'
  - '@mantine-vue/hooks@3.4.0'
  - '@mantine-vue/notifications@3.4.0'
  - '@mantine-vue/store@3.4.0'
  - '@mantine-vue/utils@3.4.0'
